# Tool Options
tool_tier: vanillahammers:emerald
tool_category: minecraft:pickaxe
break_speed: 2
attack_damage: 7
attack_speed: 1

# Hammer Options
range: 1
depth: 1
hardness_tolerance: 0

# Damageable Options
durability: 1560
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: "minecraft:emerald"

# Enchantable Options
enchantment_value: 10
enchantment_categories: ["digger", "breakable"]