# Tool Options
tool_tier: vanilla_hammers:lapis
tool_category: minecraft:pickaxe
break_speed: 1.7
attack_damage: 5
attack_speed: 2

# Hammer Options
range: 1
depth: 1
hardness_tolerance: 0

# Damageable Options
durability: 220
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: "minecraft:lapis_lazuli"

# Enchantable Options
enchantment_value: 30
enchantment_categories: ["digger", "breakable"]