# Tool Options
tool_tier: vanillahammers:obsidian
tool_category: minecraft:pickaxe
break_speed: 1.4
attack_damage: 7
attack_speed: 0.5

# Hammer Options
range: 1
depth: 1
hardness_tolerance: 0

# Damageable Options
durability: 2500
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: "minecraft:obsidian"

# Enchantable Options
enchantment_value: 5
enchantment_categories: ["digger", "breakable"]